apiVersion: v1
kind: Pod
metadata:
  name: db-app-demo
  labels:
    name: db-app-demo
    app: demo-app
spec:
  containers:
    - name: db-app
      image: redis
      ports:
        - containerPort: 6379
