apiVersion: v1
kind: Service
metadata:
  name: db-app-service
  labels:
    name: db-app-service
    app: demo-app
spec:
  ports:
    - port: 6379
      targetPort: 6379 
  selector:
    name: db-app-demo
    app: demo-app
           
