apiVersion: v1
kind: Service
metadata:
  name: postgress-app-service
  labels:
    name: postgress-app-service
    app: demo-app
spec:
  ports:
    - port: 5432 
      targetPort: 5432
  selector:
    name: postgress-app-demo
    app: demo-app
