apiVersion: app/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-app
specs:
  replicas: 1
  template:
    metadate:
      name: result-app-demo
      labels:
        name: result-app-demo
        app: demo-app
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: result-app-demo
      app: demo-app
            
    
