apiVersion: v1
kind: pod
metadate:
  name: voting-app-demo
  labels:
    name: voting-app-demo
    app: demo-app
spec:
  containers:
    - name: voting-app
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
