apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    name: voting-app-service
    app: demo-app
spec:
  type: NodePort
  ports:
    - port: 80 
      targetPort: 80
      nodePort: 30003
  selector:
    name: voting-app-demo
    app: demo-app
