apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-app
specs:
  replicas: 1
  template:
    metadata:
      name: worker-app-demo
      labels:
        name: worker-app-demo
        app: demo-app
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
  selector:
    matchLabels:
      name: worker-app-demo
      app: demo-app
     
        
