apiVersion: v1
kind: pod
metadate:
  name: worker-app-demo
  labels:
    name: worker-app-demo
    app: demo-app
spec:
  containers:
    - name: worker-app
      image: kodekloud/examplevotingapp_worker:v1
